Movieproject/movieproject/movieapp/urls.py
from django.urls import path
from . import views

app_name = 'movieapp'

urlpatterns = [
    
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add_item,name='add_items'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

Movieproject/movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Movieproject/movieproject/movieapp/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='pictures')

    def __str__(self):
        return self.name

Movieproject/movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model= Movie
        fields = ['name','desc','year','img']

Movieproject/movieproject/movieapp/views.py
from django.shortcuts import render,redirect
from django.http  import HttpResponse

from movieapp.models import Movie

from .forms import MovieForm

# Create your views here.

def index(request):
    obj = Movie.objects.all()
    content = {
        'movie_list' : obj
    }
    return render(request,'index.html',content)

def details(request,movie_id):
    movie = Movie.objects.get(id=movie_id)

    return render(request,'details.html',{'movie':movie})

    # return HttpResponse('This movie id is %s' %movie_id)
def add_item(request):
        
    if request.method == "POST":
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie = Movie(name=name,desc=desc,year=year,img=img)
        movie.save()

    return render(request,'add_item.html')

def update(request,id):
    movie = Movie.objects.get(id = id)
    form = MovieForm(request.POST or None,request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    
    return render(request,'edit.html',{'movie':movie,'form': form})

def delete(request,id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

Movieproject/movieproject/templates/add_item.html
 {% extends 'base.html' %}

 {% block body %}

<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}

  <div class="card bg-light" style="margin-top: 15px;">
    <article class="card-body mx-auto " style="max-width: 400px">
      <h4 class="card-title mt-3 text-center">Upload Movie Details</h4>
      <p class="text-center">Get start</p>
      <!-- <p class="divider-text">
        <span class="bg-light">OR</span>
      </p> -->

      <div class="form-group input-group">
        <div class="input-group-prepend">
          <span class="input-group-text"> <i class="fa fa-user"></i> </span>
        </div>
        <input
          name="name"
          class="form-control"
          placeholder="Movie Name"
          type="text"
        />
      </div>
      <div class="form-group input-group">
        <div class="input-group-prepend">
          <span class="input-group-text"> <i class="fa fa-user"></i> </span>
        </div>
        <input
          name="desc"
          class="form-control"
          placeholder="Description"
          type="text"
        />
      </div>
      <div class="form-group input-group">
        <div class="input-group-prepend">
          <span class="input-group-text"> <i class="fa fa-user"></i> </span>
        </div>
        <input
          name="year"
          class="form-control"
          placeholder="Enter year"
          type="number"
        />
      </div>
      
    <input type="file" name="img" />
    <div class="form-group" style="margin: 10px;">
        <button type="submit" class="btn btn-primary btn-block"> Submit  </button>
    </div>
    </article>
  </div>
  <!-- <input type="text" name="name" placeholder="Enter your name" />
  <input type="text" name="desc" placeholder="Enter your name" />
  <input type="number" name="year" placeholder="Enter your name" /> -->
  
  <!-- <input type="submit" value="submit" /> -->
</form>

{% endblock %}

Movieproject/movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      rel="stylesheet"
      id="bootstrap-css"
    />
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.0.8/css/all.css"
    />
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/register.css' %}" />
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'styles/style.css' %}" /> -->
    <title>Document</title>
  </head>
  <body>
    <nav class="navbar bg-body-tertiary">
      <div class="container" style="justify-content: flex-start">
        <a class="navbar-brand" href="#">
          <img
            src="https://getbootstrap.com/docs/5.3/assets/brand/bootstrap-logo.svg"
            alt="Bootstrap"
            width="30"
            height="24"
          />
        </a>
        <h5 style="text-align: right; margin-top: 10px">MovieBox</h5>
      </div>
    </nav>
    <div class="container">
      {% block body %}
      {% endblock %}
    </div>
    
    
  
  </body>
</html>

Movieproject/movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}

<form action="" method="post">

    {% csrf_token %}
    Are you want to delete?
    <input type="submit" value="Delete">

</form>

{% endblock %}

Movieproject/movieproject/templates/details.html
{% extends 'base.html' %} {% block body %}
<div class="container mt-5 mb-3">
  <div class="card mb-3" >
    <div class="row no-gutters">
      <div class="col-md-4">
        <img
          src="{{movie.img.url}}"
          class="card-img"
          alt="..."
          height="220"
          width="240"
        />
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">{{movie.name}}</h5>
          <p class="card-text">{{movie.desc}}</p>
          <p class="card-text">
            <small class="text-muted">{{movie.year}}</small>
          </p>
        </div>
        <a class="btn btn-success" href="{% url 'movieapp:update' movie.id %}"
          >Update</a
        >
        <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}"
          >Delete</a
        >
      </div>
    </div>
  </div>
</div>

{% endblock %}

Movieproject/movieproject/templates/edit.html
{% extends 'base.html' %}

{% block body %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{form.as_p}}
<input type="submit" value="submit">
</form>
{% endblock %}

Movieproject/movieproject/templates/index.html
{% extends 'base.html' %} 
{% block body %} 

<!-- {{i.name}}<br /> -->



<div class="container mt-5 mb-3">
  <div class="row">
    {% for i in movie_list %} 
    <div class="col-sm-3 p-3 mb-3 my-2 py-2">
      <div class="card " >
        
        <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">{{i.name}}</h5>
          <p class="card-text">{{i.desc}},{{i.year}}.</p>
          <a href="{%url 'movieapp:details' i.id %}" class="btn btn-primary">Details..</a>
        </div>

      </div>
    </div>
    {% endfor %}
  </div>
</div>





 {% endblock %}